version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src/api/:/app
    tty: true
    stdin_open: true
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - ${WEB_PORT}:80

    volumes:
      - ./src/api/:/app
    depends_on:
      - app

  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    ports:
      - 9000:5173
    volumes:
      - ./src/front:/app
    tty: true
    stdin_open: true
    depends_on:
      - app

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    depends_on:
      - app
    privileged: true
    container_name: selenium-test

volumes:
  mysql-volume:
